esphome:
  name: twctest

esp32:
  board: esp32-poe-iso
  framework:
    type: esp-idf

# Enable logging
logger:
  level: DEBUG
  logs:
    component: ERROR
    twc_gen2: DEBUG

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: "testwifi"
  password: ""

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Twctest Fallback Hotspot"
    password: "wvokFmWePmPC"

captive_portal:
    
uart:
  id: twc_uart
  tx_pin: GPIO4
  rx_pin: GPIO36
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1


external_components:
#  - source: github://erwin314/twc_gen2
#    components: [twc_gen2]
  - source:
      type: local
      path: /components
    components: [twc_gen2]

twc_gen2:
  uart_id: twc_uart
  flow_control_pin: 14
  read_only: false
  c1_serial: A18G0005893
  c2_serial: A18H0020359
  global_limit: 16
  c1_limit: 32
  c2_limit: 32

number:
  - platform: twc_gen2
    global_limit:
      name: TWC limiet
      min_value: 12
      max_value: 32

switch:
  - platform: twc_gen2    
    c1_allow_charging:
      restore_mode: RESTORE_DEFAULT_OFF
      name: 1 Allow Charging
    c2_allow_charging:
      restore_mode: RESTORE_DEFAULT_OFF
      name: 2 Allow Charging

text_sensor:
  - platform: twc_gen2
    c1_serial:
      name: 1 Serial
    c2_serial:
      name: 2 Serial
    c1_vin:
      name: 1 VIN
    c2_vin:
      name: 2 VIN

sensor:
  platform: twc_gen2
  c1_voltage1:
    name: 1 Voltage L1
  c1_voltage2:
    name: 1 Voltage L2
  c1_voltage3:
    name: 1 Voltage L3
  c2_voltage1:
    name: 2 Voltage L1
  c2_voltage2:
    name: 2 Voltage L2
  c2_voltage3:
    name: 2 Voltage L3

  c1_current1:
    name: 1 Current L1
  c1_current2:
    name: 1 Current L2
  c1_current3:
    name: 1 Current L3
  c2_current1:
    name: 2 Current L1
  c2_current2:
    name: 2 Current L2
  c2_current3:
    name: 2 Current L3

  c1_energy:
    name: 1 Energy
  c2_energy:
    name: 2 Energy

  c1_state:
    name: 1 State
  c2_state:
    name: 2 State

  c1_actual_current:
    name: 1 Actual Current
  c2_actual_current:
    name: 2 Actual Current
